name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest   # ✅ WinForms için Windows runner

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o publish

    # ✅ Versiyon bilgisini al (varsa csproj’dan, yoksa fallback run number)
    - name: Get project version
      id: get_version
      run: |
        $csproj = Get-ChildItem -Path JsonConverter -Filter *.csproj | Select-Object -First 1
        $versionNode = Select-Xml -Path $csproj.FullName -XPath "//Version" | ForEach-Object { $_.Node.InnerText }
        if ([string]::IsNullOrEmpty($versionNode)) {
          $versionNode = "1.0.${{ github.run_number }}"
        }
        echo "VERSION=$versionNode" >> $env:GITHUB_ENV

    - name: Zip artifact
      run: Compress-Archive -Path publish -DestinationPath app_build-${{ env.VERSION }}.zip -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app_build-${{ env.VERSION }}
        path: app_build-${{ env.VERSION }}.zip
